name: Build and deploy frontend

on:
  push:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
          
      - name: Build
        run: |
          docker login -u ${{ github.repository_owner }} -p ${{ secrets.CR_PAT }} ghcr.io && \
          docker build -t ghcr.io/mnt/itec-frontend:latest ./itec-frontend && \
          docker push ghcr.io/mnt/itec-frontend:latest

  deploy-frontend:
     needs: [ build-frontend ]
     runs-on: ubuntu-latest
     steps:
       - name: Pull & run image on server
         uses: appleboy/ssh-action@master
         with:
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.SSH_KEY }}
           script: sudo /home/docker/deploy.sh /home/docker/itec/itec-frontend latest
